# Generated by Django 5.2.7 on 2025-10-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_agendamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('confirmado', 'Pendente'), ('a_caminho', 'À caminho'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='confirmado', max_length=15),
        ),
    ]
