# Generated by Django 5.2.7 on 2025-11-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agendamentos", "0006_agendamento_status_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
